Administracion postulaciones
droopy-frba/api pull request #26
Opened 2022-07-25 02:59 UTC by joacohoyos

2022-07-25 15:49 UTC, leoguerberg requested changes

2022-07-25 15:49 UTC, leoguerberg commented on src/business/controllers/filmPostulation/dto/updateFilmPostulationDTO.dto.ts
> +  chat?: string;
@joacohoyos que serian estas dos props a futuro? streamId o chatId?

2022-07-25 15:49 UTC, leoguerberg commented on src/business/controllers/filmSearch/filmSearch.controller.ts
> +    @Query('size', ParseFloatPipe) size: number,
@joacohoyos en general para paginados es mejor pasarle `limit` y `offset` en vez de `page` y `size`, asi no estas obligado siempre a manejarte con paginas de un tamaño fijo y podrias cambiarlo a futuro

2022-07-25 15:49 UTC, leoguerberg commented on src/business/modules/filmSearch.module.ts
> +    forwardRef(() => FilmPostulationModule),
@joacohoyos porque se nos genero una dependencia circular aca? intentemos resolverla de otra forma, el `forwardRef` es un parche indicio de que estamos manejando mal el concepo de single responsability  (algo esta acoplado cuando podria no estarlo)

2022-07-25 15:49 UTC, leoguerberg commented on src/business/repositories/filmPostulation/filmPostulation.repository.ts
> +  async findBySearcAndFilmmaker(filmSearchUuid: string, filmmakerUuid: string) {
@joacohoyos typo `searc`

2022-07-25 15:49 UTC, leoguerberg commented on src/business/repositories/filmPostulation/filmPostulation.repository.ts
> +  }
@joacohoyos no podriamos unificar estos 3 servicios pasandole un param de tipo `query: FilterQuery<FilmPostulation>` (en mongoose se llama asi la interfaz, en mysql nose pero debe ser parecido)

2022-07-25 15:49 UTC, leoguerberg commented on src/business/repositories/filmmaker/filmmaker.repository.ts
> +  }
@joacohoyos si unificamos los servicios, vamos apoder unificar de igual manera el repository

2022-07-25 15:49 UTC, leoguerberg commented on src/business/services/filmPostulation.service.ts
> +      // eslint-disable-next-line quotes
@joacohoyos se necesita esto?

2022-07-25 15:50 UTC, joacohoyos commented on src/business/controllers/filmPostulation/dto/updateFilmPostulationDTO.dto.ts
> +  chat?: string;
@leoguerberg si en princpio chatId y streamId

2022-07-25 15:51 UTC, joacohoyos commented on src/business/modules/filmSearch.module.ts
> +    forwardRef(() => FilmPostulationModule),
@leoguerberg filmSearch usa el filmPostulationRepository y filmPostulation el de fimSearch. Esto pasa porque estamos usando los repositorios indistintamente

2022-07-25 15:52 UTC, joacohoyos commented on src/business/repositories/filmPostulation/filmPostulation.repository.ts
> +  }
@leoguerberg aca se armo un engendro con la idea de guido de armar un repositorio. Si vamos a hacer eso es al pedo tener el custom repository (para mi es al pedo) pero bueno, discutamoslo a la noche

2022-07-25 15:53 UTC, joacohoyos commented on src/business/services/filmPostulation.service.ts
> +      // eslint-disable-next-line quotes
@leoguerberg me estaba puteando el linter y no me queria poner a deshabilitar cosas, era mas rapido esto jaja

2022-07-26 00:04 UTC, joacohoyos commented on src/business/controllers/filmSearch/filmSearch.controller.ts
> +    @Query('size', ParseFloatPipe) size: number,
@leoguerberg listo

2022-07-26 00:04 UTC, joacohoyos commented on src/business/repositories/filmPostulation/filmPostulation.repository.ts
> +  async findBySearcAndFilmmaker(filmSearchUuid: string, filmmakerUuid: string) {
@leoguerberg listo

2022-07-28 02:03 UTC, leoguerberg approved these changes

2022-07-28 02:03 UTC, merged