30 buscar google places por nombre
droopy-frba/api pull request #31
Opened 2022-08-05 18:00 UTC by lucascheistwer

Resolves #30

2022-08-09 03:13 UTC, leoguerberg requested changes

2022-08-09 03:13 UTC, leoguerberg commented on src/business/services/filmSearch.service.ts
> +    console.log('api key: ', CONFIG.google.apiKey);
@lucascheistwer volate esto noma

2022-08-09 03:13 UTC, leoguerberg commented on src/business/services/filmSearch.service.ts
> +      });
@lucascheistwer es mas legible si haces directo 
`const response = await client.findPlaceFromText(...); return r.data.candidates.map(c => c.place_id)` y todo eso lo metes en un `try catch` para el `throw`

2022-08-09 03:13 UTC, leoguerberg commented on src/business/services/filmSearch.service.ts
> +      }),
@lucascheistwer lo mismo aca con lo de legible

2022-08-09 13:27 UTC, joacohoyos approved these changes

2022-08-09 15:22 UTC, lucascheistwer commented on src/business/services/filmSearch.service.ts
> +      }),
@leoguerberg creo que aca sí tengo que hacer el `Promise.all(ids.map() => ...)` porque tengo que iterar todos los placesId y por cada uno pegarle a la API y guardar los details en otro array. No?
Lo q si, puedo hacerlo con try catch mas limpio.
@joacohoyos

2022-08-09 17:12 UTC, joacohoyos commented on src/business/services/filmSearch.service.ts
> +      }),
creo que el try catch lo podes sacar, total tirar una BadREquestException o la excepion de google es lo mismo

2022-08-09 17:13 UTC, joacohoyos commented on src/business/services/filmSearch.service.ts
> +      }),
Ya tenemos un filter que catchea las excepciones y manda el 400 si no lo catcheas en ningun lado

2022-08-12 00:43 UTC, leoguerberg approved these changes

2022-08-12 00:43 UTC, merged